### PR TITLE
RelatedProducts & YourOutFix: Create Widget Skeleton and resolve the conflick.

### PR DESCRIPTION
**Pull request by vannguyen-vn**
@irislavie , @thecaitlinkinney @isabell-lee : please review it for me!

### CODE REVIEW

**Comment by vannguyen-vn** [comment]
Sorry, I forgot to attach the link  Trello.
https://trello.com/c/TLqliPpo

**Comment by isabell-lee** [comment]
@vannguyen-vn  Things do not look merged correctly with app.jsx and index.jsx, it looks like you're deleting some of the work that was already done.

**Comment by vannguyen-vn** [comment]
> @vannguyen-vn Things do not look merged correctly with app.jsx and index.jsx, it looks like you're deleting some of the work that was already done.

Let me check!

**Comment by isabell-lee** [comment]
Also, you do not need to import ReactDOM in any of your components. Only index.jsx needs that for ReactDOM.render().

**Pull request closed without merging**
